config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users
  resources :albums, except: [:destroy]
  resources :users,    only: [:new, :create]
  resources :sessions, only: [:new, :create]
  
  delete 'logout' => 'sessions#destroy'

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :albums
	validates :username, presence: true
	validates :password, length: { within: 6..40 }
	has_secure_password
	devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def new
		@album = Album.new
	end

	def create 
		@album = Album.new(album_params)
		
		if @album.save
			redirect_to albums_path
		else
			render :new
		end
	end

	def show
		@album = Album.find(params[:id])
	end

	def index
		@albums = Album.all
	end


	private
	def album_params
		params.require(:album).permit(:artist, :title, :year)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


	private
	def current_user
	  #if @current_user is not defined set it equal to the result using the session hash given that exists
	  @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def user_signed_in?
	  current_user.present?
	end

	helper_method :current_user, :user_signed_in?
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		@user = User.new
	end

	def create #creates new session, not new user
	  @user = User.find_by_username(params[:username])

	  if @user.authenticate(params[:password])
	    session[:user_id] = @user.id
	    redirect_to root_path
	  else
	    flash[:error] = "Invalid username & password combination"
	    render :new
	  end
	end

	def destroy #logout user
		session[:user_id] = nil 
  	redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
        redirect_to root_path
    else #saving the user is unsuccessful
        #populate the flash hash with the errors present in active record
        flash[:error] = @user.errors.full_messages.to_sentence 
        render :new
    end
  end

private
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_album.html.erb
<li><%= link_to album.title, album %></li>

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>
	<% if @album.errors.any? %>
		<ul>
		<% @album.errors.full_messages.each do |error| %>
		<li><%= error %></li>
		<% end %>
		</ul>
	<% end %>

		<%= f.label :artist %>
		<%= f.text_field :artist %>

		<%= f.label :album %>
		<%= f.text_field :title %>

		<%= f.label :year %>
		<%= f.text_field :year %>

		<%= f.submit %>
<% end %>

app/views/albums/index.html.erb
<h1>Articles Index</h1>

  <ul>
  	<% @albums.each do |a| %>
  	<!-- a.title = album name && a.artist = artist name && a = id, if available -->
  	<li><%= link_to a.artist, a %>
  		<ul><%= a.title %></ul>
  	</li>

  	<% end %>
  </ul>

app/views/albums/new.html.erb
<h1>Create a new album</h1>

<%= render 'form' %>

app/views/albums/show.html.erb
<p><%= @album.artist %></p>
<p><%= @album.title  %></p>
<p><%= @album.year   %></p>

<%= link_to 'Delete', @album, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicLab</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
	<%= link_to "Home", root_path %>
	<%= link_to "Add a new album", new_album_path %>
 	<%= link_to "Logout", logout_path, method: :delete %>
<% else %>
  <%= link_to "Login", new_session_path %>
  <%= link_to "Sign up", new_user_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Users#new signup page</h1>
<p>Find me in app/views/users/new.html.erb</p>

<!-- form_for always references a @model -->
<%= form_for @user, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>

    <%= f.label :username %><br>
    <%= f.text_field :username %><br>

    <%= f.label :password %><br>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Signup" %>

  <% flash.each do |name, msg| -%>
 		<%= content_tag :div, msg, class: name %>
	<% end -%>

<% end %>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
  <h3>Congrats! You are successfully logged in, <%= current_user.username %>!</h3><br>
  <h5>Here's a list of all your albums:</h5>


<% else %>
  <!-- <%= link_to "Signup", new_user_path %> -->
  <!-- handled by layouts/application.html.erb -->
<% end %>